name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Transfer files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_DNS }} "mkdir -p /home/ubuntu/app"
          scp -o StrictHostKeyChecking=no -i private_key.pem -r . ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/home/ubuntu/app

      - name: Build and run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            cd /home/ubuntu/app
            sudo systemctl restart docker  # Ensures Docker is running
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF
