name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Transfer files to EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r * ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/home/ubuntu/app

      - name: Build and run Docker Compose on EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            cd /home/ubuntu/app
            docker compose down
            docker compose build
            docker compose up -d
          EOF
